# Generated by Django 3.2.4 on 2021-08-22 15:53

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('expert', models.CharField(max_length=15)),
                ('point', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.filepath)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
    ]
